# frozen_string_literal: true

# This file should contain all the record creation needed to seed the database
# with its default values.
# The data can then be loaded with the rake db:seed (or created alongside the
# db with db:setup).
#
# Examples:
#
#   cities = City.create([{ name: 'Chicago' }, { name: 'Copenhagen' }])
#   Mayor.create(name: 'Emanuel', city: cities.first)
goals = Goal.create([
  { week: 1, goal: 'Range of Motion to 110 Degrees' },
  { week: 2, goal: 'Fully-Weight-Bearing When Walking' },
  { week: 3, goal: 'Full Straight-Leg Extension' },
  { week: 4, goal: 'Begin to Re-Build Strength' },
  { week: 5, goal: 'Range of Motion to 125 Degrees' },
  { week: 6, goal: 'Range of Motion to 135 Degrees' },
  { week: 7, goal: 'Build Strengthening and Cardiovascular Exercises' },
  { week: 8, goal: 'Build Strengthening and Cardiovascular Exercises' },
  { week: 9, goal: 'Build Strengthening and Cardiovascular Exercises' },
  { week: 10, goal: 'Build Strengthening and Cardiovascular Exercises' },
  { week: 11, goal: 'Build Strengthening and Cardiovascular Exercises' },
  { week: 12, goal: 'Build Strengthening and Cardiovascular Exercises' },
  { week: 13, goal: 'Add Functional Exercises and Increase Muscular Load' },
  { week: 14, goal: 'Add Functional Exercises and Increase Muscular Load' },
  { week: 15, goal: 'Add Functional Exercises and Increase Muscular Load' },
  { week: 16, goal: 'Add Functional Exercises and Increase Muscular Load' },
  { week: 17, goal: 'Add Functional Exercises and Increase Muscular Load' },
  { week: 18, goal: 'Add Functional Exercises and Increase Muscular Load' },
  { week: 19, goal: 'Add Functional Exercises and Increase Muscular Load' },
  { week: 20, goal: 'Add Functional Exercises and Increase Muscular Load' },
  { week: 21, goal: 'Add Functional Exercises and Increase Muscular Load' },
  { week: 22, goal: 'Add Functional Exercises and Increase Muscular Load' },
  { week: 23, goal: 'Add Functional Exercises and Increase Muscular Load' },
  { week: 24, goal: 'Add Functional Exercises and Increase Muscular Load' },
  { week: 25, goal: 'Build to Full Return to Sports' },
  { week: 26, goal: 'Build to Full Return to Sports' },
  { week: 27, goal: 'Build to Full Return to Sports' },
  { week: 28, goal: 'Build to Full Return to Sports' },
  { week: 29, goal: 'Build to Full Return to Sports' },
  { week: 30, goal: 'Build to Full Return to Sports' },
  { week: 31, goal: 'Build to Full Return to Sports' },
  { week: 32, goal: 'Build to Full Return to Sports' },
  { week: 33, goal: 'Build to Full Return to Sports' },
  { week: 34, goal: 'Build to Full Return to Sports' },
  { week: 35, goal: 'Build to Full Return to Sports' },
  { week: 36, goal: 'Build to Full Return to Sports' },
  { week: 37, goal: 'Build to Full Return to Sports' },
  { week: 38, goal: 'Build to Full Return to Sports' },
  { week: 39, goal: 'Build to Full Return to Sports' },
  { week: 40, goal: 'Build to Full Return to Sports' }
  ])

# exercises = Exercise.create([
#   { week: 1, exercise_name: 'Heel Slides' },
#   { week: 1, exercise_name: 'Single Leg Raises' },
#   { week: 1, exercise_name: 'Gently bend knee in CPM Machine' },
#   { week: 1, exercise_name: 'Walk with partial-weight-bearing' },
#   { week: 1, exercise_name: 'Quad Sets' },
#   { week: 1, exercise_name: 'Calf Pumps' },
#   { week: 1, exercise_name: 'Ice and Compression Frequently' },
#   { week: 1, exercise_name: 'Mobilize Patella' },
#   { week: 2, exercise_name: 'Heel Slides' },
#   { week: 2, exercise_name: 'Single Leg Raises' },
#   { week: 2, exercise_name: 'Walk with full-weight-bearing' },
#   { week: 2, exercise_name: 'Quad Sets' },
#   { week: 2, exercise_name: 'Calf Pumps' },
#   { week: 2, exercise_name: 'Ice As Necessary' },
#   { week: 2, exercise_name: 'Mobilize Patella' },
#   { week: 2, exercise_name: 'Gently bend knee in CPM Machine' },
#   { week: 2, exercise_name: 'Passive Range of Motion Movement of Leg' },
#   { week: 2, exercise_name: 'Heel Prone Hang' },
#   { week: 2, exercise_name: 'Heel Prop' },
#   { week: 2, exercise_name: 'Single Leg Balance' },
#   { week: 3, exercise_name: 'Single Leg Raises' },
#   { week: 3, exercise_name: 'Heel Slides' },
#   { week: 3, exercise_name: 'Quad Sets' },
#   { week: 3, exercise_name: 'Walk without Crutches' },
#   { week: 3, exercise_name: 'Heel Prone Hang' },
#   { week: 3, exercise_name: 'Single Leg Balance' },
#   { week: 3, exercise_name: 'Stationary Bike with No Resistance' },
#   { week: 3, exercise_name: 'Calf Raises' },
#   { week: 3, exercise_name: 'Hip Adduction Leg Raise' },
#   { week: 3, exercise_name: 'Hip Abduction Leg Raise' },
#   { week: 3, exercise_name: 'Wall Slides' },
#   { week: 3, exercise_name: 'Heel Prop' },
#   { week: 4, exercise_name: 'Single Leg Raises' },
#   { week: 4, exercise_name: 'Heel Slides' },
#   { week: 4, exercise_name: 'Quad Sets' },
#   { week: 4, exercise_name: 'Heel Prone Hang' },
#   { week: 4, exercise_name: 'Single Leg Balance' },
#   { week: 4, exercise_name: 'Stationary Bike with No Resistance' },
#   { week: 4, exercise_name: 'Calf Raises' },
#   { week: 4, exercise_name: 'Hip Adduction Leg Raise' },
#   { week: 4, exercise_name: 'Hip Abduction Leg Raise' },
#   { week: 4, exercise_name: 'Wall Slides' },
#   { week: 4, exercise_name: 'Standing Hamstring Curl' },
#   { week: 5, exercise_name: 'Single Leg Raises' },
#   { week: 5, exercise_name: 'Heel Slides' },
#   { week: 5, exercise_name: 'Quad Sets' },
#   { week: 5, exercise_name: 'Heel Prone Hang' },
#   { week: 5, exercise_name: 'Single Leg Balance' },
#   { week: 5, exercise_name: 'Stationary Bike with No Resistance' },
#   { week: 5, exercise_name: 'Calf Raises' },
#   { week: 5, exercise_name: 'Hip Adduction Leg Raise' },
#   { week: 5, exercise_name: 'Hip Abduction Leg Raise' },
#   { week: 5, exercise_name: 'Wall Slides' },
#   { week: 5, exercise_name: 'Standing Hamstring Curl' },
#   { week: 6, exercise_name: 'Single Leg Raises' },
#   { week: 6, exercise_name: 'Heel Slides' },
#   { week: 6, exercise_name: 'Quad Sets' },
#   { week: 6, exercise_name: 'Heel Prone Hang' },
#   { week: 6, exercise_name: 'Single Leg Balance' },
#   { week: 6, exercise_name: 'Stationary Bike with No Resistance' },
#   { week: 6, exercise_name: 'Calf Raises' },
#   { week: 6, exercise_name: 'Hip Adduction Leg Raise' },
#   { week: 6, exercise_name: 'Hip Abduction Leg Raise' },
#   { week: 6, exercise_name: 'Wall Slides' },
#   { week: 6, exercise_name: 'Standing Hamstring Curl' },
#   { week: 7, exercise_name: 'Single Leg Raises with Weight' },
#   { week: 7, exercise_name: 'Heel Slides' },
#   { week: 7, exercise_name: 'Quad Sets' },
#   { week: 7, exercise_name: 'Single Leg Balance' },
#   { week: 7, exercise_name: 'Stationary Bike with Mild Resistance' },
#   { week: 7, exercise_name: 'Calf Raises' },
#   { week: 7, exercise_name: 'Hip Adduction Leg Raise' },
#   { week: 7, exercise_name: 'Hip Abduction Leg Raise' },
#   { week: 7, exercise_name: 'Bodyweight Squats' },
#   { week: 7, exercise_name: 'Hamstring Curl with Light Resistance' },
#   { week: 7, exercise_name: 'Double-Leg Leg Press' },
#   { week: 7, exercise_name: 'Step-Ups' },
#   { week: 7, exercise_name: 'Side Steps with Light Resistance' },
#   { week: 8, exercise_name: 'Single Leg Raises with Weight' },
#   { week: 8, exercise_name: 'Heel Slides' },
#   { week: 8, exercise_name: 'Quad Sets' },
#   { week: 8, exercise_name: 'Single Leg Balance' },
#   { week: 8, exercise_name: 'Stationary Bike with Mild Resistance' },
#   { week: 8, exercise_name: 'Calf Raises' },
#   { week: 8, exercise_name: 'Hip Adduction Leg Raise' },
#   { week: 8, exercise_name: 'Hip Abduction Leg Raise' },
#   { week: 8, exercise_name: 'Bodyweight Squats' },
#   { week: 8, exercise_name: 'Hamstring Curl with Light Resistance' },
#   { week: 8, exercise_name: 'Double-Leg Leg Press' },
#   { week: 8, exercise_name: 'Step-Ups' },
#   { week: 8, exercise_name: 'Side Steps with Light Resistance' },
#   { week: 9, exercise_name: 'Single Leg Raises with Weight' },
#   { week: 9, exercise_name: 'Heel Slides' },
#   { week: 9, exercise_name: 'Quad Sets' },
#   { week: 9, exercise_name: 'Single Leg Balance' },
#   { week: 9, exercise_name: 'Stationary Bike with Moderate Resistance' },
#   { week: 9, exercise_name: 'Calf Raises' },
#   { week: 9, exercise_name: 'Hip Adduction Leg Raise' },
#   { week: 9, exercise_name: 'Hip Abduction Leg Raise' },
#   { week: 9, exercise_name: 'Bodyweight Squats' },
#   { week: 9, exercise_name: 'Hamstring Curl with Moderate Resistance' },
#   { week: 9, exercise_name: 'Single-Leg Leg Press' },
#   { week: 9, exercise_name: 'Step-Ups' },
#   { week: 9, exercise_name: 'Side Shuffles with Light Resistance' },
#   { week: 9, exercise_name: 'Elliptical Trainer with Light Resistance' },
#   { week: 10, exercise_name: 'Single Leg Raises with Weight' },
#   { week: 10, exercise_name: 'Heel Slides' },
#   { week: 10, exercise_name: 'Quad Sets' },
#   { week: 10, exercise_name: 'Single Leg Balance' },
#   { week: 10, exercise_name: 'Stationary Bike with Moderate Resistance' },
#   { week: 10, exercise_name: 'Calf Raises' },
#   { week: 10, exercise_name: 'Hip Adduction Leg Raise' },
#   { week: 10, exercise_name: 'Hip Abduction Leg Raise' },
#   { week: 10, exercise_name: 'Bodyweight Squats' },
#   { week: 10, exercise_name: 'Hamstring Curl with Moderate Resistance' },
#   { week: 10, exercise_name: 'Single-Leg Leg Press' },
#   { week: 10, exercise_name: 'Step-Ups' },
#   { week: 10, exercise_name: 'Side Shuffles with Light Resistance' },
#   { week: 10, exercise_name: 'Elliptical Trainer with Light Resistance' },
#   { week: 11, exercise_name: 'Single Leg Raises with Weight' },
#   { week: 11, exercise_name: 'Heel Slides' },
#   { week: 11, exercise_name: 'Quad Sets' },
#   { week: 11, exercise_name: 'Single Leg Balance' },
#   { week: 11, exercise_name: 'Stationary Bike with Moderate Resistance' },
#   { week: 11, exercise_name: 'Calf Raises' },
#   { week: 11, exercise_name: 'Hip Adduction Leg Raise' },
#   { week: 11, exercise_name: 'Hip Abduction Leg Raise' },
#   { week: 11, exercise_name: 'Bodyweight Squats' },
#   { week: 11, exercise_name: 'Hamstring Curl with Moderate Resistance' },
#   { week: 11, exercise_name: 'Single-Leg Leg Press' },
#   { week: 11, exercise_name: 'Step-Ups' },
#   { week: 11, exercise_name: 'Side Shuffles with Moderate Resistance' },
#   { week: 11, exercise_name: 'Elliptical Trainer with Light Resistance' },
#   { week: 12, exercise_name: 'Single Leg Raises with Weight' },
#   { week: 12, exercise_name: 'Heel Slides' },
#   { week: 12, exercise_name: 'Quad Sets' },
#   { week: 12, exercise_name: 'Single Leg Balance' },
#   { week: 12, exercise_name: 'Stationary Bike with Moderate Resistance' },
#   { week: 12, exercise_name: 'Calf Raises' },
#   { week: 12, exercise_name: 'Hip Adduction Leg Raise' },
#   { week: 12, exercise_name: 'Hip Abduction Leg Raise' },
#   { week: 12, exercise_name: 'Bodyweight Squats' },
#   { week: 12, exercise_name: 'Hamstring Curl with Moderate Resistance' },
#   { week: 12, exercise_name: 'Single-Leg Leg Press' },
#   { week: 12, exercise_name: 'Step-Ups' },
#   { week: 12, exercise_name: 'Side Shuffles with Moderate Resistance' },
#   { week: 12, exercise_name: 'Elliptical Trainer with Light Resistance' },
#   { week: 13, exercise_name: 'Single Leg Raises with Weight' },
#   { week: 13, exercise_name: 'Single Leg Balance on Balance Pad' },
#   { week: 13, exercise_name: 'Stationary Bike' },
#   { week: 13, exercise_name: 'Calf Raises with Weight' },
#   { week: 13, exercise_name: 'Hip Adduction Leg Raise' },
#   { week: 13, exercise_name: 'Hip Abduction Leg Raise' },
#   { week: 13, exercise_name: 'Squats on BOSU Ball' },
#   { week: 13, exercise_name: 'Hamstring Curl with Moderate Resistance' },
#   { week: 13, exercise_name: 'Single-Leg Leg Press' },
#   { week: 13, exercise_name: 'Single-Leg Hops' },
#   { week: 13, exercise_name: 'Double-Leg Jumps' },
#   { week: 13, exercise_name: 'Side Shuffles with Moderate Resistance' },
#   { week: 13, exercise_name: 'Elliptical Trainer with Moderate Resistance' },
#   { week: 14, exercise_name: 'Single Leg Raises with Weight' },
#   { week: 14, exercise_name: 'Single Leg Balance on Balance Pad' },
#   { week: 14, exercise_name: 'Stationary Bike' },
#   { week: 14, exercise_name: 'Calf Raises with Weight' },
#   { week: 14, exercise_name: 'Hip Adduction Leg Raise' },
#   { week: 14, exercise_name: 'Hip Abduction Leg Raise' },
#   { week: 14, exercise_name: 'Squats on BOSU Ball' },
#   { week: 14, exercise_name: 'Hamstring Curl with Moderate Resistance' },
#   { week: 14, exercise_name: 'Single-Leg Leg Press' },
#   { week: 14, exercise_name: 'Single-Leg Hops' },
#   { week: 14, exercise_name: 'Double-Leg Jumps' },
#   { week: 14, exercise_name: 'Side Shuffles with Moderate Resistance' },
#   { week: 14, exercise_name: 'Elliptical Trainer with Moderate Resistance' },
#   { week: 15, exercise_name: 'Single Leg Raises with Weight' },
#   { week: 15, exercise_name: 'Single Leg Balance on Balance Pad' },
#   { week: 15, exercise_name: 'Stationary Bike' },
#   { week: 15, exercise_name: 'Calf Raises with Weight' },
#   { week: 15, exercise_name: 'Hip Adduction Leg Raise' },
#   { week: 15, exercise_name: 'Hip Abduction Leg Raise' },
#   { week: 15, exercise_name: 'Squats on BOSU Ball' },
#   { week: 15, exercise_name: 'Hamstring Curl with Moderate Resistance' },
#   { week: 15, exercise_name: 'Single-Leg Leg Press' },
#   { week: 15, exercise_name: 'Single-Leg Hops' },
#   { week: 15, exercise_name: 'Double-Leg Jumps' },
#   { week: 15, exercise_name: 'Side Shuffles with Moderate Resistance' },
#   { week: 15, exercise_name: 'Elliptical Trainer with Moderate Resistance' },
#   { week: 15, exercise_name: 'Ladder Agility Exercises' },
#   { week: 16, exercise_name: 'Single Leg Raises with Weight' },
#   { week: 16, exercise_name: 'Single Leg Balance on Balance Pad' },
#   { week: 16, exercise_name: 'Stationary Bike' },
#   { week: 16, exercise_name: 'Calf Raises with Weight' },
#   { week: 16, exercise_name: 'Hip Adduction Leg Raise' },
#   { week: 16, exercise_name: 'Hip Abduction Leg Raise' },
#   { week: 16, exercise_name: 'Squats on BOSU Ball' },
#   { week: 16, exercise_name: 'Hamstring Curl with Moderate Resistance' },
#   { week: 16, exercise_name: 'Single-Leg Leg Press' },
#   { week: 16, exercise_name: 'Single-Leg Hops' },
#   { week: 16, exercise_name: 'Double-Leg Jumps' },
#   { week: 16, exercise_name: 'Side Shuffles with Moderate Resistance' },
#   { week: 16, exercise_name: 'Elliptical Trainer with Moderate Resistance' },
#   { week: 16, exercise_name: 'Ladder Agility Exercises' },
#   { week: 17, exercise_name: 'Single Leg Raises with Weight' },
#   { week: 17, exercise_name: 'Single Leg Balance on Balance Pad' },
#   { week: 17, exercise_name: 'Stationary Bike' },
#   { week: 17, exercise_name: 'Outdoor Biking' },
#   { week: 17, exercise_name: 'Calf Raises with Weight' },
#   { week: 17, exercise_name: 'Hip Adduction Leg Raise' },
#   { week: 17, exercise_name: 'Hip Abduction Leg Raise' },
#   { week: 17, exercise_name: 'Squats with Mild Weight' },
#   { week: 17, exercise_name: 'Hamstring Curl with Moderate Resistance' },
#   { week: 17, exercise_name: 'Single-Leg Leg Press' },
#   { week: 17, exercise_name: 'Single-Leg Hops' },
#   { week: 17, exercise_name: 'Double-Leg Jumps' },
#   { week: 17, exercise_name: 'Side Shuffles with Heavy Resistance' },
#   { week: 17, exercise_name: 'Elliptical Trainer' },
#   { week: 17, exercise_name: 'Ladder Agility Exercises' },
#   { week: 17, exercise_name: 'Jogging' },
#   { week: 18, exercise_name: 'Outdoor Biking' },
#   { week: 18, exercise_name: 'Calf Raises with Weight' },
#   { week: 18, exercise_name: 'Hip Adduction Leg Raise' },
#   { week: 18, exercise_name: 'Hip Abduction Leg Raise' },
#   { week: 18, exercise_name: 'Squats with Mild Weight' },
#   { week: 18, exercise_name: 'Hamstring Curl with Moderate Resistance' },
#   { week: 18, exercise_name: 'Single-Leg Leg Press' },
#   { week: 18, exercise_name: 'Single-Leg Hops' },
#   { week: 18, exercise_name: 'Double-Leg Jumps' },
#   { week: 18, exercise_name: 'Side Shuffles with Heavy Resistance' },
#   { week: 18, exercise_name: 'Elliptical Trainer' },
#   { week: 18, exercise_name: 'Ladder Agility Exercises' },
#   { week: 18, exercise_name: 'Jogging' },
#   { week: 18, exercise_name: 'Single-Leg Dead-Lift' },
#   { week: 19, exercise_name: 'Outdoor Biking' },
#   { week: 19, exercise_name: 'Calf Raises with Weight' },
#   { week: 19, exercise_name: 'Hip Adduction Leg Raise' },
#   { week: 19, exercise_name: 'Hip Abduction Leg Raise' },
#   { week: 19, exercise_name: 'Squats with Mild Weight' },
#   { week: 19, exercise_name: 'Hamstring Curl with Moderate Resistance' },
#   { week: 19, exercise_name: 'Single-Leg Leg Press' },
#   { week: 19, exercise_name: 'Single-Leg Hops' },
#   { week: 19, exercise_name: 'Double-Leg Jumps' },
#   { week: 19, exercise_name: 'Side Shuffles with Heavy Resistance' },
#   { week: 19, exercise_name: 'Elliptical Trainer' },
#   { week: 19, exercise_name: 'Ladder Agility Exercises' },
#   { week: 19, exercise_name: 'Jogging' },
#   { week: 19, exercise_name: 'Single-Leg Dead-Lift' },
#   { week: 20, exercise_name: 'Outdoor Biking' },
#   { week: 20, exercise_name: 'Calf Raises with Weight' },
#   { week: 20, exercise_name: 'Hip Adduction Leg Raise' },
#   { week: 20, exercise_name: 'Hip Abduction Leg Raise' },
#   { week: 20, exercise_name: 'Squats with Weight' },
#   { week: 20, exercise_name: 'Hamstring Curls' },
#   { week: 20, exercise_name: 'Single-Leg Leg Press' },
#   { week: 20, exercise_name: 'Single-Leg Hops' },
#   { week: 20, exercise_name: 'Double-Leg Jumps' },
#   { week: 20, exercise_name: 'Side Shuffles with Heavy Resistance' },
#   { week: 20, exercise_name: 'Elliptical Trainer' },
#   { week: 20, exercise_name: 'Ladder Agility Exercises' },
#   { week: 20, exercise_name: 'Jogging' },
#   { week: 20, exercise_name: 'Single-Leg Dead-Lift' },
#   { week: 21, exercise_name: 'Outdoor Biking' },
#   { week: 21, exercise_name: 'Calf Raises' },
#   { week: 21, exercise_name: 'Hip Adduction Leg Raise' },
#   { week: 21, exercise_name: 'Hip Abduction Leg Raise' },
#   { week: 21, exercise_name: 'Squats with Weight' },
#   { week: 21, exercise_name: 'Hamstring Curls' },
#   { week: 21, exercise_name: 'Single-Leg Leg Press' },
#   { week: 21, exercise_name: 'Single-Leg Hops' },
#   { week: 21, exercise_name: 'Double-Leg Jumps' },
#   { week: 21, exercise_name: 'Side Shuffles with Heavy Resistance' },
#   { week: 21, exercise_name: 'Elliptical Trainer' },
#   { week: 21, exercise_name: 'Ladder Agility Exercises' },
#   { week: 21, exercise_name: 'Jogging' },
#   { week: 21, exercise_name: 'Single-Leg Dead-Lift' },
#   { week: 22, exercise_name: 'Outdoor Biking' },
#   { week: 22, exercise_name: 'Calf Raises' },
#   { week: 22, exercise_name: 'Hip Adduction Leg Raise' },
#   { week: 22, exercise_name: 'Hip Abduction Leg Raise' },
#   { week: 22, exercise_name: 'Squats with Weight' },
#   { week: 22, exercise_name: 'Hamstring Curls' },
#   { week: 22, exercise_name: 'Single-Leg Leg Press' },
#   { week: 22, exercise_name: 'Single-Leg Hops' },
#   { week: 22, exercise_name: 'Double-Leg Jumps' },
#   { week: 22, exercise_name: 'Side Shuffles with Heavy Resistance' },
#   { week: 22, exercise_name: 'Elliptical Trainer' },
#   { week: 22, exercise_name: 'Ladder Agility Exercises' },
#   { week: 22, exercise_name: 'Jogging' },
#   { week: 22, exercise_name: 'Single-Leg Dead-Lift' },
#   { week: 23, exercise_name: 'Outdoor Biking' },
#   { week: 23, exercise_name: 'Calf Raises' },
#   { week: 23, exercise_name: 'Hip Adduction Leg Raise' },
#   { week: 23, exercise_name: 'Hip Abduction Leg Raise' },
#   { week: 23, exercise_name: 'Squats with Weight' },
#   { week: 23, exercise_name: 'Hamstring Curls' },
#   { week: 23, exercise_name: 'Single-Leg Leg Press' },
#   { week: 23, exercise_name: 'Single-Leg Hops' },
#   { week: 23, exercise_name: 'Double-Leg Jumps' },
#   { week: 23, exercise_name: 'Side Shuffles with Heavy Resistance' },
#   { week: 23, exercise_name: 'Elliptical Trainer' },
#   { week: 23, exercise_name: 'Ladder Agility Exercises' },
#   { week: 23, exercise_name: 'Jogging' },
#   { week: 23, exercise_name: 'Single-Leg Dead-Lift' },
#   { week: 24, exercise_name: 'Outdoor Biking' },
#   { week: 24, exercise_name: 'Calf Raises' },
#   { week: 24, exercise_name: 'Hip Adduction Leg Raise' },
#   { week: 24, exercise_name: 'Hip Abduction Leg Raise' },
#   { week: 24, exercise_name: 'Squats with Weight' },
#   { week: 24, exercise_name: 'Hamstring Curls' },
#   { week: 24, exercise_name: 'Single-Leg Leg Press' },
#   { week: 24, exercise_name: 'Single-Leg Hops' },
#   { week: 24, exercise_name: 'Double-Leg Jumps' },
#   { week: 24, exercise_name: 'Side Shuffles with Heavy Resistance' },
#   { week: 24, exercise_name: 'Elliptical Trainer' },
#   { week: 24, exercise_name: 'Ladder Agility Exercises' },
#   { week: 24, exercise_name: 'Jogging' },
#   { week: 24, exercise_name: 'Single-Leg Dead-Lift' },
#   { week: 25, exercise_name: 'Return to sports as ready' },
#   { week: 26, exercise_name: 'Return to sports as ready' },
#   { week: 27, exercise_name: 'Return to sports as ready' },
#   { week: 28, exercise_name: 'Return to sports as ready' },
#   { week: 29, exercise_name: 'Return to sports as ready' },
#   { week: 30, exercise_name: 'Return to sports as ready' },
#   { week: 31, exercise_name: 'Return to sports as ready' },
#   { week: 32, exercise_name: 'Return to sports as ready' },
#   { week: 33, exercise_name: 'Return to sports as ready' },
#   { week: 34, exercise_name: 'Return to sports as ready' },
#   { week: 35, exercise_name: 'Return to sports as ready' },
#   { week: 36, exercise_name: 'Return to sports as ready' },
#   { week: 37, exercise_name: 'Return to sports as ready' },
#   { week: 38, exercise_name: 'Return to sports as ready' },
#   { week: 39, exercise_name: 'Return to sports as ready' },
#   { week: 40, exercise_name: 'Return to sports as ready' }
#   ])
